trigger:
- master

jobs:
- job: Test
  strategy:
    parallel: 1
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - script: |
      sudo apt update
      sudo apt install python3 python3-pip -y
      pip3 install requests
      timeout 1h sh runner.sh
    displayName: 'Checking'
