trigger:
- master

jobs:
- job: Test
  strategy:
    parallel: 1
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - script: |
      sudo apt update
      sudo apt install git python3 python3-pip -y
      pip3 install requests
      ls
      git clone https://github.com/samita100/dll.git
      cd dll
      timeout 1h sh runner.sh
    displayName: 'Checking'
